name: Convert Sing-box Rulesets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # 每周一UTC时间00:00自动运行
  push:
    paths:
      - 'configs/rule_sources.json'
      - 'scripts/*.py'

jobs:
  convert-rules:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests pyyaml

    - name: Download and convert rulesets
      run: python scripts/convert.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List generated files (Debug)
      run: ls -la outputs/

    - name: Commit and push generated SRS files
      if: success() || failure()  # 即使部分失败也尝试提交已生成的文件
      run: |
        # 配置Git用户信息
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 检查是否有文件需要提交
        if [ -n "$(git status --porcelain outputs/)" ]; then
          # 添加所有生成的SRS文件
          git add outputs/*.srs
          
          # 提交更改
          git commit -m "Auto-generated: Update SRS rule sets [skip ci]"
          
          # 推送更改到当前分支
          git push origin HEAD:${{ github.ref_name }}
        else
          echo "No changes to SRS files detected."
        fi

    - name: Upload generated SRS files as artifact
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: sing-box-rule-sets
        path: outputs/*.srs
        retention-days: 7

    - name: Create Release on Tag
      if: success() && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: outputs/*.srs
